version: '3.8'

services :

  mysql:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysqldb
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mediscreen
    ports:
      - "3307:3306"


  mongodb:
    image: mongo
    volumes:
      - db_data:/var/lib/mongodb
    container_name: mongodb
    ports:
      - "27018:27017"
    restart: always
    

  patient-microservice:
    image: patient-microservice
    build:
      context: Patient
      dockerfile: dockerfile
    ports:
      - "9021:9011"
    depends_on:
      - mysql




  patient-historical:
    image: patient-historical
    build:
      context: PatientHistorical
      dockerfile: dockerfile
    ports:
      - "9022:9012"
    depends_on:
      - mongodb


  patient-diabetes-risk:
    image: diabetes-risk
    build:
      context: PatientDiabetesRisk
      dockerfile: dockerfile
    ports:
      - "9023:9013"
    depends_on:
      - patient-microservice
    restart: always


  ui-microservice:
    image: ui-microservice
    build:
      context: Ui
      dockerfile: dockerfile
    ports:
      - "9020:9010"
    depends_on:
      - patient-microservice
      - patient-diabetes-risk
      - patient-historical
    restart: always

volumes:
  db_data: {}