version: '3.8'

services :

 mysql:
  image: mysql:latest
  volumes:
    - db_data:/var/lib/mysql
  container_name: mysqldb
  environment:
    MYSQL_USER: user
    MYSQL_ROOT_PASSWORD: user
    MYSQL_DATABASE: mediscreen
  ports:
    - "3307:3306"



 mongodb:
  image: mongo
  volumes:
    - db_data:/var/lib/mongodb
  container_name: mongodb
  ports:
    - "27018:27017"
  restart: always


 patient-microservice:
  image: patient-microservice
  container_name: patient-microservice
  build:
    context: Patient
    dockerfile: dockerfile
  ports:
    - "9011:9011"


 patient-historical:
    image: patient-historical
    container_name: patient-historical
    build:
      context: PatientHistorical
      dockerfile: dockerfile
    ports:
      - "9012:9012"
    depends_on:
      - mongodb


 patient-diabetes-risk:
    image: patient-diabetes-risk
    container_name: patient-diabetes-risk
    build:
      context: PatientDiabetesRisk
      dockerfile: dockerfile
    ports:
      - "9013:9013"
    depends_on:
      - patient-microservice
    restart: always


 ui-microservice:
    image: ui-microservice
    container_name: ui-microservice
    build:
      context: Ui
      dockerfile: dockerfile
    ports:
      - "9010:9010"
    depends_on:
      - patient-microservice
      - patient-diabetes-risk
      - patient-historical
    restart: always



volumes:
  db_data: {}

